name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Count files
        run: echo "FILES=$(find . -path ./.git -prune -o -type f -print | wc -l)" >> $GITHUB_ENV

      - name: Greet Student
        run: echo "Hello ${{ vars.STUDENT_NAME }}, your files count are $FILES"